name: Upload Release Asset

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  # Artifact name
                  name: build # optional, default is artifact
                  # A file, directory or wildcard pattern that describes what to upload
                  path: ./build
    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            #Get version from package.json
            - name: Get NPM Package Version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - uses: actions/download-artifact@v4
              with:
                  name: build
            #unzip
            - run: unzip build.zip -d build
            - name: Create a Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.package-version.outputs.current-version }}
                  release_name: Release by Action(${{ github.run_number }})
                  draft: false
                  prerelease: false
            - name: Upload Release Asset
              id: upload-release-asset-bundle
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/bundle.js
                  asset_name: bundle.js
                  asset_content_type: application/javascript
            - name: Upload Release Asset
              id: upload-release-asset-cjs
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/cjs.js
                  asset_name: cjs.css
                  asset_content_type: application/javascript
            - name: Upload Release Asset
              id: upload-release-asset-umd
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/umd.js
                  asset_name: umd.js
                  asset_content_type: application/javascript
            - name: zip Types
              run: zip -r ./build/types.zip ./build/types
            - name: zip Doc
              run: zip -r ./build/doc.zip ./build/doc
            - name: Upload Release Asset
              id: upload-release-asset-types
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/types.zip
                  asset_name: types.zip
                  asset_content_type: application/zip
            - name: Upload Release Asset
              id: upload-release-asset-doc
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/doc.zip
                  asset_name: doc.zip
                  asset_content_type: application/javascript
